/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Fts */

#ifndef _Included_Fts
#define _Included_Fts
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Fts
 * Method:    indexer
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Fts_indexer(JNIEnv*, jobject, jstring, jstring);

/*
 * Class:     Fts
 * Method:    searcher
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Fts_searcher(JNIEnv*, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
